export { getPosts, getComments, getReplies } from './getResources'
export { getPost, getComment, getReply } from './getResource'
export { releasePost, releaseComment, releaseReply } from './releaseResource'
export { default as reportResource } from './reportResource'
export { default as evaluateResource } from './evaluateResource'
export { default as deleteResource } from './deleteResrouce'
