export { default as getResources } from './getResources'
export { default as getResource } from './getResource'
export { default as releaseResource } from './releaseResource'
export { default as reportResource } from './reportResource'
export { default as evaluateResource } from './evaluateResource'
export { default as deleteResource } from './deleteResrouce'
