export { iterator } from './iterator'
export { URLSearchParams } from './URLSearchParams'
export { querySelector } from './querySelector'
export { querySelectorAll } from './querySelectorAll'
export { getTag } from './getTag'
